modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="mod_ne_ebu"
version="1.0.0"
displayName="mod_ne_ebu"
displayURL="https://cuboserver.net"
credits="semen"
authors="arniks"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.mod_ne_ebu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.mod_ne_ebu]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration